[package]
name = "vis-rs"
version = "0.1.0"
authors = ["Joey Sacchini <joey@sacchini.net>"]
edition = "2024"
rust-version = "1.85"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.103"
fftw = "0.8.0"
sdl2 = "0.38.0"
rayon = "1.12.0"
num-rational = "0.4.2"
serde = { version = "1.0.228", features = ["derive"] }
serde_yaml = "0.9.34"

#[profile.dev]
#opt-level = 1

[profile.release]
lto = "fat"
opt-level = 3
codegen-units = 1
overflow-checks = false
incremental = false
panic = "abort"
